
version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/app
        links:
            - php
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/app
        working_dir: /app
        links:
            - mysql
        #extra_hosts:
        #- "host.docker.internal:host-gateway"
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_CONFIG: 
                client_host=host.docker.internal
                client_port=9003
                log=/app/xdebug.log
                start_with_request=yes
                idekey=VSCODE
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'pass'
            MYSQL_DATABASE: 'social'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - "8080:80"
        environment:
          - PMA_HOST='mysql'
          - MYSQL_ROOT_PASSWORD='pass' 
          - PMA_ARBITRARY=1        
volumes:
    mysqldata:
